services:
  auth-service:
    build: ./auth-service
    restart: unless-stopped
    ports:
      - "${PORT_AUTH}:8001"
    environment:
      - DB_HOST=db-auth
      - POSTGRES_PORT=5432
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${DB_NAME_AUTH}
      - JWT_PRIVATE_KEY=${JWT_PRIVATE_KEY}
      - JWT_PUBLIC_KEY=${JWT_PUBLIC_KEY}
    depends_on:
      - db-auth
    networks:
      - greenfield-net

  db-auth:
    image: postgres:15-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${DB_NAME_AUTH}
    volumes:
      - authdb_data:/var/lib/postgresql/data
    networks:
      - greenfield-net

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - "${PORT_PGADMIN}:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - greenfield-net
  
  redis-weather:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "${PORT_REDIS_WEATHER}:6379"
    volumes:
      - redis_weather_data:/data
    networks:
      - greenfield-net
  
  weather-service:
    build: ./weather-service
    restart: unless-stopped
    ports:
      - "${PORT_WEATHER}:8002"
    environment:
      - REDIS_URL=redis://redis-weather:6379
      - WEATHER_API_KEY=${WEATHER_API_KEY}
      - JWT_PUBLIC_KEY=${JWT_PUBLIC_KEY}
    depends_on:
      - redis-weather
    networks:
      - greenfield-net
  
  image-service:
    build: ./image-service
    restart: unless-stopped
    environment:
      - JWT_PUBLIC_KEY=${JWT_PUBLIC_KEY}
    ports:
      - "${PORT_IMAGE}:8003"
    networks:
      - greenfield-net
  
  mqtt-broker:
    image: eclipse-mosquitto:2.0
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    networks:
      - greenfield-net
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
    healthcheck:
      test: ["CMD", "mosquitto_pub", "-h", "localhost", "-p", "1883", "-t", "healthcheck", "-m", "ok"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  rabbit-mq:
    image: rabbitmq:3-management-alpine
    restart: unless-stopped
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS}
    ports:
      - "5672:5672"
      - "${PORT_RABBIT_MGMT}:15672"
    networks:
      - greenfield-net
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  iot-gateway:
    build: ./iot-gateway
    restart: unless-stopped
    environment:
      - MQTT_HOST=${MQTT_HOST}
      - MQTT_PORT=${MQTT_PORT}
      - MQTT_TOPIC=${MQTT_TOPIC_PATTERN}
      - RABBITMQ_URL=${RABBITMQ_URL}
      - RABBITMQ_EXCHANGE=${RABBITMQ_SENSORS_EXCHANGE}
    stop_grace_period: 2s
    depends_on:
      rabbit-mq:
        condition: service_healthy
      mqtt-broker:
        condition: service_healthy
      rabbit-infrastructure:
        condition: service_completed_successfully
    networks:
      - greenfield-net
  
  sensor-simulator:
    build: ./sensor-simulator
    restart: unless-stopped
    environment:
      - MQTT_HOST=${MQTT_HOST}
      - MQTT_PORT=${MQTT_PORT}
    stop_grace_period: 2s
    depends_on:
      mqtt-broker:
        condition: service_healthy
      iot-gateway:
        condition: service_started
    networks:
      - greenfield-net
  
  field-service:
    build: ./field-service
    restart: unless-stopped
    ports:
      - "${PORT_FIELD}:8004"
    environment:
      - RABBITMQ_URL=${RABBITMQ_URL}
      - RABBITMQ_FIELD_QUEUE=${RABBITMQ_FIELD_QUEUE}
      - DB_HOST=db-fields
      - POSTGRES_PORT=5432
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${DB_NAME_FIELDS}
      - JWT_PUBLIC_KEY=${JWT_PUBLIC_KEY}
      - WEATHER_SERVICE_URL=${URL_WEATHER_SERVICE}
    depends_on:
      rabbit-mq:
        condition: service_healthy
      db-fields:
        condition: service_started
      rabbit-infrastructure:
        condition: service_completed_successfully
    networks:
      - greenfield-net
  
  db-fields:
    image: postgres:15-alpine
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${DB_NAME_FIELDS}
    volumes:
      - fieldsdb_data:/var/lib/postgresql/data
    networks:
      - greenfield-net
  
  intelligent-service:
    build: ./intelligent-service
    restart: unless-stopped
    ports:
      - "${PORT_INTELLIGENT}:8005"
    environment:
      - RABBITMQ_URL=${RABBITMQ_URL}
      - RABBITMQ_INTELLIGENT_QUEUE=${RABBITMQ_INTELLIGENT_QUEUE}
      - RABBITMQ_ALERTS_EXCHANGE=${RABBITMQ_ALERTS_EXCHANGE}
      - DB_HOST=db-intelligent
      - POSTGRES_PORT=5432
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${DB_NAME_INTELLIGENT}
      - JWT_PUBLIC_KEY=${JWT_PUBLIC_KEY}
      - FIELD_SERVICE_URL=${URL_FIELD_SERVICE}
      - REDIS_URL=redis://redis-intelligent:6379
    depends_on:
      rabbit-mq:
        condition: service_healthy
      db-intelligent:
        condition: service_started
      redis-intelligent:
        condition: service_started
      rabbit-infrastructure:
        condition: service_completed_successfully
    networks:
      - greenfield-net
  
  db-intelligent:
    image: postgres:15-alpine
    restart: unless-stopped
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${DB_NAME_INTELLIGENT}
    volumes:
      - intelligentdb_data:/var/lib/postgresql/data
    networks:
      - greenfield-net
  
  redis-intelligent:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "${PORT_REDIS_INTELLIGENT}:6379"
    volumes:
      - redis_intelligent_data:/data
    networks:
      - greenfield-net
  
  rabbit-infrastructure:
    build: ./rabbit-infrastructure
    restart: "no"
    environment:
      - RABBITMQ_URL=${RABBITMQ_URL}
      - RABBITMQ_SENSORS_EXCHANGE=${RABBITMQ_SENSORS_EXCHANGE}
      - RABBITMQ_ALERTS_EXCHANGE=${RABBITMQ_ALERTS_EXCHANGE}
      - RABBITMQ_FIELD_QUEUE=${RABBITMQ_FIELD_QUEUE}
      - RABBITMQ_INTELLIGENT_QUEUE=${RABBITMQ_INTELLIGENT_QUEUE}
      - RABBITMQ_FIELD_ROUTING_KEY=${RABBITMQ_FIELD_ROUTING_KEY}
    depends_on:
      rabbit-mq:
        condition: service_healthy
    networks:
      - greenfield-net
    
  notification-service:
    build: ./notification-service
    restart: unless-stopped
    ports:
      - "${PORT_NOTIFICATION}:8006"
    environment:
      - RABBITMQ_URL=${RABBITMQ_URL}
      - RABBITMQ_SENSORS_EXCHANGE=${RABBITMQ_SENSORS_EXCHANGE}
      - RABBITMQ_ALERTS_EXCHANGE=${RABBITMQ_ALERTS_EXCHANGE}
      - RABBITMQ_FIELD_ROUTING_KEY=${RABBITMQ_FIELD_ROUTING_KEY}
      - RABBITMQ_ALERTS_ROUTING_KEY=${RABBITMQ_ALERTS_ROUTING_KEY}
      - JWT_PUBLIC_KEY=${JWT_PUBLIC_KEY}
      - FIELD_SERVICE_URL=${URL_FIELD_SERVICE}
      - REDIS_URL=redis://redis-notifications:6379
    depends_on:
      rabbit-mq:
        condition: service_healthy
      rabbit-infrastructure:
        condition: service_completed_successfully
    networks:
      - greenfield-net
  
  redis-notifications:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "${PORT_REDIS_NOTIFICATIONS}:6379"
    volumes:
      - redis_notifications_data:/data
    networks:
      - greenfield-net
  
  api-gateway:
    build: ./api-gateway
    restart: unless-stopped
    ports:
      - "${PORT_API_GATEWAY}:8000"
    environment:
      - AUTH_SERVICE_URL=${URL_AUTH_SERVICE}
      - WEATHER_SERVICE_URL=${URL_WEATHER_SERVICE}
      - IMAGE_SERVICE_URL=${URL_IMAGE_SERVICE}
      - FIELD_SERVICE_URL=${URL_FIELD_SERVICE}
      - INTELLIGENT_SERVICE_URL=${URL_INTELLIGENT_SERVICE}
      - NOTIFICATION_SERVICE_URL=${URL_NOTIFICATION_SERVICE}
      - REDIS_URL=redis://redis-api-gateway:6379
      - JWT_PUBLIC_KEY=${JWT_PUBLIC_KEY}
    depends_on:
      - auth-service
      - weather-service
      - image-service
      - field-service
      - intelligent-service
      - notification-service
    networks:
      - greenfield-net
  
  redis-api-gateway:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "${PORT_REDIS_API}:6379"
    volumes:
      - redis_api_gateway_data:/data
    networks:
      - greenfield-net
  
  frontend:
    build: ./frontend
    restart: unless-stopped
    ports:
      - "${PORT_FRONTEND}:5173"
    environment:
      - REACT_APP_API_GATEWAY_URL=${PUBLIC_API_GATEWAY_URL}
    depends_on:
      - api-gateway
    networks:
      - greenfield-net

volumes:
  authdb_data:
  pgadmin_data:
  redis_weather_data:
  rabbitmq_data:
  mosquitto_data:
  mosquitto_log:
  fieldsdb_data:
  intelligentdb_data:
  redis_intelligent_data:
  redis_notifications_data:
  redis_api_gateway_data:

networks:
  greenfield-net: